name: GCP IAM Roles manual to terraform pipeline

on:
  push:
    branches:
      - main

jobs:
  install-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip

  authenticate:
    runs-on: ubuntu-latest
    needs: install-dependencies
    steps:
      - id: 'auth'
        name: Authenticating gcloud
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_SA_KEY_NEW }}'
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'

  update-data:
    runs-on: ubuntu-latest
    needs: authenticate
    steps:
      - name: Run python file to get all the principles and roles in data.json
        run: python3 main.py
      - name: Commit updated data.json
        run: |
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add .
          git commit -m "Update data.json"

  apply-terraform:
    runs-on: ubuntu-latest
    needs: update-data
    steps:
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
      - name: Initialize Terraform
        run: terraform init
      - name: Apply Terraform changes
        run: terraform apply -auto-approve

  commit-state:
    runs-on: ubuntu-latest
    needs: apply-terraform
    steps:
      - name: Commit state files
        run: |
          git add .
          git commit -m "Update state files"
          git push origin main
